### ISSUE TITLE
Could you also add how to use, Demo!

### ISSUE THREAD

**Issue by jsroyal** [kbrsh/slash#1]
It will help to other to give a demo after getting an overview of the project.
I went through the twice the readme file but not able to understand what it does this project.
What is a use case for it?

**Comment by kbrsh** [comment]
It's a hash function. A non cryptographic hash function. This one can be used on a set of bytes and can return a 64 bit hash value. It's intended for hash tables, simple checksums, etc.

The demo is in the README. You install this project, and then include the header file which will bundle the Assembly.

```c
#include "slash.h"

const unsigned char *key = "Slash";
unsigned long long hash = slash(key);
```

**Comment by kbrsh** [comment]
Closing for now, let me know if you need anything, and feel free to reopen this.
